services:
  - type: web
    plan: free
    name: prince-md
    runtime: docker
    region: Frankfurt
    branch: main
    repo: https://github.com/Armashahzan/PRINCE-MD_V1
    #buildCommand: |
    #  apt-get update && \
    #  apt-get install -y ffmpeg && \
    #  npm install
    autoDeploy: true
    healthCheckPath: /
    #startCommand: npm start
    envVars:
      - key: SESSION_ID
        value: "YOUR_SESSION_ID"
